export { ReactComponent as community } from "./community.svg";
export { ReactComponent as trophy } from "./trophy.svg";
export { ReactComponent as gameController } from "./gameController.svg";
export { ReactComponent as vialSolid } from "./vial-solid.svg";
export { ReactComponent as Home } from "./home.svg";
export { ReactComponent as DiscordSolid } from "./discordSolid.svg";
export { ReactComponent as powerOffSolid} from "./powerOffSolid.svg";
export { ReactComponent as cogSolid} from "./cogSolid.svg";
export { ReactComponent as bellSolid} from "./bellSolid.svg";
export { ReactComponent as bellRegular} from "./bellRegular.svg";
